### ISSUE TITLE
[CRITICAL] ubuntu hirsute `21.04` and impish `21.10` officially reached to `EOL`

### ISSUE THREAD

**Issue by SaicharanKandukuri** [RandomCoderOrg/ubuntu-on-android#178]
Ubuntu 21.04 which is the current stable version of udroid reached to end of life on `January 20, 2022`
This leads to errors in apt release fetch and the whole build is un-upgradable now!

> it's officially time to end support for `ubuntu 21.04` and move to impish ASAP!
<hr>

### TODO
- [X] Add temporary redirection to install ubuntu `impish` instead of hirsute
- [X] Merger `V3` branch and move planned things to the next release
- [X] set `impish` to default
- [x] Add warning on `hirsute` install ( add patch to force upgrade everything to impish )

<hr>

- #177

**Comment by AnninoDr4** [comment]
This includes `impish` too
![image](https://user-images.githubusercontent.com/92148685/180639430-5f41d97a-25a2-498e-a578-dde90f774d59.png)

**Comment by SaicharanKandukuri** [comment]
Need to release an upgrade patch soon!
